name: CI

on:
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]
  workflow_dispatch:

jobs:
  zap:
    runs-on: macos-latest

    steps:
       - name: Checkout repo content
         uses: actions/checkout@v2
       - name: Install dependencies
         run: |
          pip3 install wget
       - name: Zap Casks
         run: |
          python3 zapAll.py
       - name: Commit files 
         run: |
          git config --local user.name "b3z"
          git config --local user.email "b3z@zeppel.eu"
          git add zappedCasks
          git commit -m "Generate zaps"
       - name: Push changes # push the output folder to your repo
         uses: ad-m/github-push-action@master
         with:
          github_token: ${{ secrets.AUTOZAP_TOKEN }}
          force: true
        #- name: export index
            
